### ISSUE TITLE
Large files processing kills due to lack of RAM

### ISSUE THREAD

**Issue by banderlog** [alephdata/cronodump#18]
I have 180GB db, and when I try to convert it to CSV I run out of memory very fast (64 GB RAM), is there a way to do some sort of pipe thing or anything else?

**Comment by erdgeist** [comment]
With the changes in https://github.com/alephdata/cronodump/pull/19, the memory footprint now should be around the size of the range of what `CroBank.tad` weighs.

If even that is too much, the PR adds an option (`--compact`) to trade 15 % more conversion time with a lot less memory consumption, typically it's static and less 10 MB.

**Comment by banderlog** [comment]
I guess I need a large swap then😅

**Comment by erdgeist** [comment]
No. Why? Did you try the PR? It was made specifically to not use as much memory. Just go ahead and please try it. As I wrote, for me there was no significant difference in conversion speed using the PR, but if you use the `--compact` option to use even less memory, then you will have to wait a little more, around 15 % more time than without the `--compact` flag.

**Comment by erdgeist** [comment]
The PR is merged. Closing as fixed.

**Comment by banderlog** [comment]
>No. Why? 

Because, if my memory serve, I have DB with ~80GB CroBank.tad :D
