### ISSUE TITLE
Error with "croconvert"

### ISSUE THREAD

**Issue by JohnnnyBeGood** [alephdata/cronodump#5]
Hello! An error occurs while converting:
**bin/croconvert --csv ~/........path........**

_WARN: expected dbinfo to start with 0x03
ERROR decoding db definition: 'charmap' codec can't decode byte 0x98 in position 115: character maps to <undefined>
This could possibly mean that you need to try with the --strucrack option_

when executing the command: **bin/crodump --strucrack recdump**  values ​​are displayed from the database:
1: 01cbe8efe5f6ea1e38......
2: 01d1eef7e81e38393830......
3: 01cceef1eae2e01e......
4: 01d2f3ebe01e38........
******************

**bin/crodump strudump -v -a ~/.......path.......**

error:  **WARN: expected dbinfo to start with 0x03**

Thanks

**Comment by nlitsme** [comment]
The recdump output with the `--strucrack` option looks like cp1251 encoded text. You can see this by adding the `-a` option after recdump.


Did you try to add the `--strucrack` option before the `strudump` command?
so:
    crodump --strucrack -v -a ~/.....

and similar for croconvert:

    croconvert --strucrack --csv ~/....

**Comment by JohnnnyBeGood** [comment]
Thank you very much!
Adding the ` --strucrack ` option in `bin/croconvert --strucrack --csv` fixed the error

thanks for clarifying the option ` -a `, I didn't read your instructions carefully

I wanted to clarify why the error occurs: 

_- Warning: Field Definition Section 2 not marked with a 2_

_- Record 3993320 too short: -- 01 1b 08 00 51 ...... (many characters)_

**Comment by JohnnnyBeGood** [comment]
Thank you very much!
Adding the ` --strucrack ` option in `bin/croconvert --strucrack --csv` fixed the error

thanks for clarifying the option ` -a `, I didn't read your instructions carefully

I wanted to clarify why the error occurs: 

_- Warning: Field Definition Section 2 not marked with a 2_

_- Record 3993320 too short: -- 01 1b 08 00 51 ...... (many characters)_

**Comment by JohnnnyBeGood** [comment]
Would you like to add the ability to split the output file if there are a lot of rows in the database?
Let's say there are more than a million or tens of millions of them in the  СronosPro database

**Comment by nlitsme** [comment]
If you really want to: you could use a tool like [split](https://www.gnu.org/software/coreutils/manual/html_node/split-invocation.html#split-invocation).

Since your original problem was solved, I will close this issue.
