### ISSUE TITLE
Not correct Date parse in croconvert.

### ISSUE THREAD

**Issue by 06opoTeHb** [alephdata/cronodump#6]
I want to say a big thanks for you. Everything works perfectly. The only thing that does not work quite correctly for me is the date conversion. For example, if in Сronos the date looks like 18.07.1962, then in the CSV I get 620718. Like in  mirror :). I tried several bases, all results the same.  Could you fix this? Thanks in advance.

**Comment by 01100001011011000110010101111000000010** [comment]
Hi there. I have the same. Would be great if the developers added the possibility to choose format of the date. It's actually YYMMDD format.
